### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by devtanc**

### CODE REVIEW

**Comment by devtanc** [comment]
Some thoughts:

**Comment by devtanc** [comment]
Accessing local/session storage is all sync by default. Wrapping those functions in async stuff just adds unnecessary complexity. If I want to use sync functions in some promise chain, I can simply use them like:

```js
someFunction()
.then(() => localstorage.getItem('key'))
.then(retrievedValue => {
  // do something with value
})
```

**Comment by devtanc** [comment]
Using `someFunc(...args) {...}` is only really useful when you don't know how many args will be passed in. For any _known_ values, you should be explicit in your declarations so that your code is clear to read. You know that they will pass in some key or array of keys, then some value, so name the arguments that way so that those reading the code don't have to guess what `args[0]` is.

**Comment by devtanc** [comment]
Since the two storage mechanisms

1. Are globally accessible without instantiation
2. Have equivalent contracts [getItem, setItem, ...etc]

allow the user to simply pass them in, rather than adding the complexity of a local mapping of your set functions to theirs. This way the user always explicitly asks for a certain storage type, but can default to the internal default of localStorage. This gives the added benefit of the user being able to pass in literally any storage system (not just local/session) that upholds that same contract (as shown in the tests that use the `node-localstorage` library).

**Comment by devtanc** [comment]
For debug logs, use `console.debug` not `console.log` to fit with convention. Also, I think that the system of logging I put in is simpler both in implementation and in complexity. I think the fact that the user just needs to pass in `{ debug: true }` is a little more standard than the original `{ logMessages: true }`, but that's more opinion than anything.

**Comment by devtanc** [comment]
I changed the default namespace to 'SimpleCache_' just to be a little more explicit. Personal preference to use longer names rather than abbreviations.

**Comment by devtanc** [comment]
Obviously I like to use yarn...

**Comment by stetsmando** [comment]
@devtanc you're the best! Thanks for the feedback 👍 I'm going through your code now and will be posting updates as I do. I have reasons behind doing things the way I did so I might not accept everything, but at first glance I do like some changes your proposed.

**Comment by devtanc** [comment]
Oh no worries, I don't care if you accept any of it. It's all just feedback, not really change requests. Just figured this was the easiest way to both give feedback and show what I mean at the same time, since it's such a simple library as is.

**Comment by stetsmando** [comment]
Totally, I appreciate you taking the time though.

**Comment by devtanc** [comment]
Convention in something like Redis is that there is an internal process that handles the removal of expired items. In your original code, if I never access an item again, it will never actually be removed from the cache. In this case, it's probably not a big deal, since it's designed for short-term usage, but I added the `setTimeout` system so that every value in the cache has it's own timeout in the browser's timeout table that will cause the value to be asynchronously removed when the expiration time is hit. Since this is all handled by the browser, and setTimeouts are cleared when the window is closed, this ends up being a rather safe option, and doesn't affect the runtime of the library.

The one weakness here is that local storage lasts longer than the window, so if the window is closed, the timeouts will be gone, but the values will remain, causing a potential for a sort of memory leak into local storage over multiple sessions that use this simple cache.

**Comment by devtanc** [comment]
Yeah, just forgot them in the tests. Just a second.

**Comment by stetsmando** [comment]
I'm working my from the top of your comments down...

**Comment by devtanc** [comment]
I think the one feature that is no longer in there is that, when using bulk set you can't specify the ttl on the objects individually. I removed this since I consider it to be bad practice to alter those objects, since they are the actual object being stored. Either set the ttl as a value on all of them, as a group, or change what's passed into be something like:

```js
set([{
  key: 'key',
  value: 'value',
  ttl: 5000,
}, {...}, ...])
```

That way you never touch the object they want inserted, and if the object they need in the cache needs a ttl value that doesn't have anything to do with the library, then they can do that, since their object is stored in the `value` prop instead. This separates your library's logic from the user's data.

**Comment by devtanc** [comment]
One thing I don't like in what I wrote is that if you want to set a customm ttl on a bulk operation you have to add extra commas, and that's messy. It would be better to figure out a different way to pass these values.

```js
set([['k', 'v'],['l','w']], /*value skipped*/, /* store possibly skipped */, 12000)
```

**Comment by stetsmando** [comment]
On the note of them passing in the store they'd like to use, I have plans to add more to this as far as stores are concerned. The next one that jumps out to me is Cookies, but I haven't thought through it very much. Having an abstraction allows the library to do more without the user thinking about it. It's meant to be simple and if we had any store that doesn't use the same `getItem`, `setItem`, `removeItem` paradigm then it would require a major version change to support since the APIs would all change. So I like having them abstracted away behind either a function or a flag of some kind.

**Comment by stetsmando** [comment]
I wrote this using ES6 classes because they're cleaner than having everything in a function. So I would want that to stay for sure.

**Comment by stetsmando** [comment]
I actually sat down to start adding tests to this and I like how you've done it, so I'm going to steal that for sure 😂

**Comment by stetsmando** [comment]
I love the `debug: true` convention so I'll add that for sure.

**Comment by stetsmando** [comment]
Making the namespace longer is fine with me too 👍

**Comment by stetsmando** [comment]
One note about `console.debug` is that it doesn't show up in the console by default. Chrome makes you select `verbose` from it's drop down to see this. I could go either way on this one but I tend to lean on making it easier to see your output without having to make an additional menu selection.

**Comment by stetsmando** [comment]
Using the ES6 spread operator with`...args` allows the methods to be overloaded without having to remap value names. Since the function signatures are fairly simple I didn't see a need to remap the values to variables, but I think it's worth doing for code maintainability. The only real downside is not being able to use default values in the function call, but I think it's cleaner.

**Comment by devtanc** [comment]
Might be better to create your own wrapper around cookie that implements getItem/setItem/etc... within the library and make it another of the exports. Just makes it so that this section of the library doesn't have to worry about that abstraction. Then future storage devices are just added to that second export.

```js
import { SimpleCache, Stores } from 'simple-cache'

const cache = new SimpleCache({ store: Stores.cookie })
// ...
```

**Comment by stetsmando** [comment]
Love that idea ☝️

**Comment by devtanc** [comment]
I get what you're saying about overloading, but I don't think I see the need for overloading the functions at all, really.

**Comment by stetsmando** [comment]
The point of caching values is so they persist for a certain amount of time. In the case of local storage you may have values that only change once a day so It makes sense to cache them for that period. If you cache a value that never gets accessed that's on you. Adding in a bunch of setTimeout calls to attempt to clean stuff up just adds unneeded cycles to the event loop. I think the practice of keeping them in the store until they're either cleared manually or by code is fine. If you have a value that's less important just store it in session storage rather than local storage. I guess the point I'm getting at is I don't see a time where somebody will cache stuff they aren't going to access again later. That's the whole point.

**Comment by stetsmando** [comment]
Dude you've given me some awesome feedback and I thank you for it! 🎉I'm going to take in some of your suggestions for sure. I plan on adding them in this weekend. I'll shoot you a message when I'm done just to see if we can meet in the middle on some of these items 👍

**Comment by devtanc** [comment]
That's fine. I'm just talking in terms of keeping with cache convention. The setTimeout functions that build up are tracked by the browser, not your library, on a separate thread, and so they don' affect performance until they run. When they run, they will remove the item from the cache and improve the performance of your access, since it will return quickly, rather  than evaluating the item in the cache and making date comparisons.

**Comment by devtanc** [comment]
Glad I could give some useful feedback :)

**Pull request closed without merging**
